version: "3.3"

services:
  rmq:
    image: rabbitmq:3.7-management-alpine
    ports:
    - 5672:5672
    - 15672:15672
    environment:
     - RABBITMQ_NODENAME=node@rmq
     - RABBITMQ_DEFAULT_USER=${RABBITMQ_DEFAULT_USER}
     - RABBITMQ_DEFAULT_PASS=${RABBITMQ_DEFAULT_PASS}
    volumes:
      - ./docker-volumes/rmq:/var/lib/rabbitmq/mnesia/node@rmq
    restart: unless-stopped

  mongo:
    image: mongo:3.4-jessie
    ports:
    - 127.0.0.1:27017:27017
    volumes:
    - ./docker-volumes/mongo:/data/db
    restart: unless-stopped

  worker:
    tty: true
    build: ./worker
    environment:
    - RABBITMQ_USER=${RABBITMQ_DEFAULT_USER}
    - RABBITMQ_PASS=${RABBITMQ_DEFAULT_PASS}
    - RABBITMQ_HOST=rmq
    - RABBITMQ_PORT=5672
    - MONGO_URL=mongo:27017
    - DEBUG=${DEBUG}
    depends_on:
    - mongo
    - rmq
    restart: unless-stopped
